title: "Organomicon"
description: "The book of named organic reactions. Most of which are named after dead people."

# Root-domain GitHub Pages settings
url: "https://organomicon.github.io"
baseurl: ""

# Theme + plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes"

markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  reactions:
    output: true
    permalink: /reactions/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      toc: true
      toc_label: "Contents"
      toc_icon: "list"
      sidebar:
        nav: "main"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      sidebar:
        nav: "main"
